// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt955-6VAzxcoeb0rwUeAjc7WwhM_s6-k',
    appId: '1:1014756039444:android:2272ea03bca40d1deb0001',
    messagingSenderId: '1014756039444',
    projectId: 'unitymain-41590',
    storageBucket: 'unitymain-41590.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJvvHiVReNosFQM3ox6RoBnnOIgb-RuKE',
    appId: '1:1014756039444:ios:8bf5c8aff4f94f8aeb0001',
    messagingSenderId: '1014756039444',
    projectId: 'unitymain-41590',
    storageBucket: 'unitymain-41590.firebasestorage.app',
    iosBundleId: 'com.example.unityMain',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIWl0SIav294vlZx6VZf-6Cmfrm0gFGPc',
    appId: '1:1014756039444:web:7075642bccae964ceb0001',
    messagingSenderId: '1014756039444',
    projectId: 'unitymain-41590',
    authDomain: 'unitymain-41590.firebaseapp.com',
    storageBucket: 'unitymain-41590.firebasestorage.app',
    measurementId: 'G-PKV0M3DDMS',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJvvHiVReNosFQM3ox6RoBnnOIgb-RuKE',
    appId: '1:1014756039444:ios:8bf5c8aff4f94f8aeb0001',
    messagingSenderId: '1014756039444',
    projectId: 'unitymain-41590',
    storageBucket: 'unitymain-41590.firebasestorage.app',
    iosBundleId: 'com.example.unityMain',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIWl0SIav294vlZx6VZf-6Cmfrm0gFGPc',
    appId: '1:1014756039444:web:260829a86e6a7f42eb0001',
    messagingSenderId: '1014756039444',
    projectId: 'unitymain-41590',
    authDomain: 'unitymain-41590.firebaseapp.com',
    storageBucket: 'unitymain-41590.firebasestorage.app',
    measurementId: 'G-X9VZ1BEQRX',
  );

}
